from .base import *  # noqa: F403

DEBUG = False  # noqa: F405
ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]  # noqa: F405

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
