/* This file is generated by scripts/sdk/generate.py. */
import type { ApiPaths } from "@careos/types";

export interface ClientOptions {
  baseUrl: string;
  fetch?: typeof fetch;
}

export function createClient(options: ClientOptions) {
  const fetcher = options.fetch ?? fetch;
  const baseUrl = options.baseUrl.replace(/\/$/, "");

  async function request<Path extends keyof ApiPaths & string, Method extends keyof ApiPaths[Path] & string>(
    path: Path,
    method: Method
  ): Promise<ApiPaths[Path][Method]> {
    const response = await fetcher(`${baseUrl}${path}`, { method: String(method) });
    if (!response.ok) {
      throw new Error(`Request failed: ${response.status}`);
    }
    return response.json() as Promise<ApiPaths[Path][Method]>;
  }

  return {
    get_ai_review_items: () => request("/ai-review-items/", "GET"),
    get_ai_review: () => request("/ai/review/", "GET"),
    get_ai_review__review_id_: () => request("/ai/review/{review_id}/", "GET"),
    get_audit_events: () => request("/audit-events/", "GET"),
    get_billing_plans: () => request("/billing/plans/", "GET"),
    get_billing_subscription: () => request("/billing/subscription/", "GET"),
    get_compliance_bundles__bundle_id__download: () => request("/compliance/bundles/{bundle_id}/download/", "GET"),
    get_compliance_reports: () => request("/compliance/reports/", "GET"),
    get_compliance_submissions: () => request("/compliance/submissions/", "GET"),
    get_conversations: () => request("/conversations/", "GET"),
    get_conversations__conversation_id_: () => request("/conversations/{conversation_id}/", "GET"),
    get_episodes: () => request("/episodes/", "GET"),
    get_episodes__episode_id_: () => request("/episodes/{episode_id}/", "GET"),
    get_episodes__episode_id__compliance_bundles: () => request("/episodes/{episode_id}/compliance/bundles/", "GET"),
    get_episodes__episode_id__evidence: () => request("/episodes/{episode_id}/evidence/", "GET"),
    get_episodes__episode_id__timeline: () => request("/episodes/{episode_id}/timeline/", "GET"),
    get_evidence: () => request("/evidence/", "GET"),
    get_evidence__evidence_id_: () => request("/evidence/{evidence_id}/", "GET"),
    get_evidence__evidence_id__events: () => request("/evidence/{evidence_id}/events/", "GET"),
    get_exports: () => request("/exports/", "GET"),
    get_exports__export_id_: () => request("/exports/{export_id}/", "GET"),
    get_exports__export_id__download: () => request("/exports/{export_id}/download/", "GET"),
    get_health: () => request("/health/", "GET"),
    get_healthz: () => request("/healthz/", "GET"),
    get_integrations: () => request("/integrations/", "GET"),
    get_integrations_api_keys: () => request("/integrations/api-keys/", "GET"),
    get_me: () => request("/me/", "GET"),
    get_metrics: () => request("/metrics/", "GET"),
    get_notifications: () => request("/notifications/", "GET"),
    get_orgs_current: () => request("/orgs/current/", "GET"),
    get_orgs_invites: () => request("/orgs/invites/", "GET"),
    get_orgs_members: () => request("/orgs/members/", "GET"),
    get_patients: () => request("/patients/", "GET"),
    get_patients__patient_id_: () => request("/patients/{patient_id}/", "GET"),
    get_portal_episodes: () => request("/portal/episodes/", "GET"),
    get_portal_episodes__episode_id_: () => request("/portal/episodes/{episode_id}/", "GET"),
    get_portal_me: () => request("/portal/me/", "GET"),
    get_portal_notifications: () => request("/portal/notifications/", "GET"),
    get_privacy_consents: () => request("/privacy/consents/", "GET"),
    get_privacy_dsar_exports: () => request("/privacy/dsar/exports/", "GET"),
    get_privacy_dsar_exports__export_id__download: () => request("/privacy/dsar/exports/{export_id}/download/", "GET"),
    get_readyz: () => request("/readyz/", "GET"),
    get_work_items: () => request("/work-items/", "GET"),
  };
}
