/* This file is generated by scripts/sdk/generate.py. */
import type { ApiPaths } from "@careos/types";

export interface ClientOptions {
  baseUrl: string;
  fetch?: typeof fetch;
}

export function createClient(options: ClientOptions) {
  const fetcher = options.fetch ?? fetch;
  const baseUrl = options.baseUrl.replace(/\/$/, "");

  async function request<Path extends keyof ApiPaths & string, Method extends keyof ApiPaths[Path] & string>(
    path: Path,
    method: Method
  ): Promise<ApiPaths[Path][Method]> {
    const response = await fetcher(`${baseUrl}${path}`, { method: String(method) });
    if (!response.ok) {
      throw new Error(`Request failed: ${response.status}`);
    }
    return response.json() as Promise<ApiPaths[Path][Method]>;
  }

  return {
    get_audit_events: () => request("/audit-events/", "GET"),
    get_health: () => request("/health/", "GET"),
    get_me: () => request("/me/", "GET"),
    get_orgs_current: () => request("/orgs/current/", "GET"),
  };
}
