/* This file is generated by scripts/sdk/generate.py. */
/* eslint-disable */

export interface AuditEvent {
  action: string;
  created_at: string;
  id: number;
  target_id: string;
  target_type: string;
}

export interface AuditEventList {
  results: AuditEvent[];
}

export interface HealthResponse {
  status: string;
}

export interface MeResponse {
  email: string | null;
  id: number;
  organization_id: number;
  role: string;
}

export interface OrgResponse {
  id: number;
  name: string;
  slug: string;
}

export interface ApiPaths {
  "/audit-events/": {
    GET: AuditEventList;
  };
  "/health/": {
    GET: HealthResponse;
  };
  "/me/": {
    GET: MeResponse;
  };
  "/orgs/current/": {
    GET: OrgResponse;
  };
}
