/* This file is generated by scripts/sdk/generate.py. */
/* eslint-disable */

export interface AIReviewCreateRequest {
  input_type: string;
  payload?: Record<string, unknown>;
}

export interface AIReviewCreateResponse {
  created_at: string;
  id: number;
  input_type: string;
  status: string;
}

export interface AIReviewDetail {
  created_at: string;
  error?: string;
  id: number;
  input_type: string;
  model_name?: string;
  model_provider?: string;
  model_version?: string;
  output?: Record<string, unknown>;
  payload?: Record<string, unknown>;
  status: string;
}

export interface AIReviewItem {
  created_at: string;
  decided_at?: string | null;
  decided_by?: number | null;
  decision_note?: string;
  episode_id?: number | null;
  id: number;
  kind: string;
  payload_json?: Record<string, unknown>;
  status: string;
}

export interface AIReviewItemDecision {
  decision: string;
  note?: string;
}

export interface AIReviewItemDecisionResponse {
  decision_note?: string;
  id: number;
  status: string;
}

export interface AIReviewItemList {
  results: AIReviewItem[];
}

export interface AIReviewListResponse {
  results: AIReviewDetail[];
}

export interface AdminAuthAuditRequest {
  outcome: string;
  username: string;
}

export interface AuditEvent {
  action: string;
  actor_id?: number | null;
  created_at: string;
  id: number;
  metadata?: Record<string, unknown>;
  request_id?: string;
  target_id: string;
  target_type: string;
}

export interface AuditEventList {
  count: number;
  page: number;
  page_size: number;
  results: AuditEvent[];
}

export interface BillingCheckoutRequest {
  cancel_url: string;
  currency?: string;
  plan_code: string;
  success_url: string;
}

export interface BillingCheckoutResponse {
  id: string;
  url: string;
}

export interface BillingPlan {
  code: string;
  currency?: string;
  entitlements?: Record<string, unknown>;
  name: string;
  seats: number;
}

export interface BillingPlanList {
  results: BillingPlan[];
}

export interface BillingSubscription {
  currency?: string | null;
  current_period_end?: string | null;
  entitlements?: Record<string, unknown>;
  plan_code?: string;
  seat_limit?: number;
  status: string;
}

export interface ConsentRecord {
  channel?: string;
  consent_type: string;
  created_at: string;
  granted: boolean;
  id: number;
  metadata?: Record<string, unknown>;
  policy_version: string;
  recorded_at: string;
  subject_id: string;
  subject_type: string;
}

export interface ConsentRecordCreateRequest {
  channel?: string;
  consent_type: string;
  granted?: boolean;
  metadata?: Record<string, unknown>;
  policy_version: string;
  subject_id: string;
  subject_type: string;
}

export interface ConsentRecordList {
  results: ConsentRecord[];
}

export interface Conversation {
  created_at: string;
  episode_id?: number | null;
  id: number;
  participants: ConversationParticipant[];
}

export interface ConversationCreateRequest {
  episode_id?: number;
  participants?: number[];
}

export interface ConversationDetailResponse {
  episode_id?: number | null;
  id: number;
  messages: Message[];
  participants: ConversationParticipant[];
}

export interface ConversationListResponse {
  results: Conversation[];
}

export interface ConversationParticipant {
  email?: string | null;
  id: number;
  username: string;
}

export interface DsarDeleteRequest {
  subject_id: string;
  subject_type: string;
}

export interface DsarExport {
  artifact_path?: string | null;
  created_at: string;
  finished_at?: string | null;
  id: number;
  status: string;
  subject_id: string;
  subject_type: string;
}

export interface DsarExportList {
  results: DsarExport[];
}

export interface DsarExportRequest {
  subject_id?: string;
  subject_type?: string;
}

export interface Episode {
  assigned_to?: number | null;
  created_at: string;
  created_by?: number | null;
  description?: string;
  id: number;
  patient_id?: number | null;
  status: string;
  title: string;
  updated_at: string;
}

export interface EpisodeCreateRequest {
  assigned_to_id?: number;
  description?: string;
  patient_id?: number;
  title: string;
}

export interface EpisodeEvent {
  created_at: string;
  created_by?: number | null;
  event_type: string;
  from_state?: string;
  from_status?: string;
  id: number;
  note?: string;
  payload_json?: Record<string, unknown>;
  to_state?: string;
  to_status?: string;
}

export interface EpisodeList {
  count: number;
  page: number;
  page_size: number;
  results: Episode[];
}

export interface EpisodeTimelineResponse {
  count: number;
  page: number;
  page_size: number;
  results: EpisodeEvent[];
}

export interface EpisodeTransitionRequest {
  note?: string;
  payload_json?: Record<string, unknown>;
  to_state: string;
  to_status?: string;
}

export interface EpisodeTransitionResponse {
  id: number;
  status: string;
}

export interface EvidenceBundle {
  artifact_path?: string | null;
  created_at: string;
  episode_id: number;
  id: number;
  manifest?: Record<string, unknown>;
}

export interface EvidenceBundleList {
  results: EvidenceBundle[];
}

export interface EvidenceCreateRequest {
  episode_id?: string;
  file: string;
  kind: string;
  patient_id?: string;
  retention_class?: string;
  retention_until?: string;
  tags?: string;
  title?: string;
}

export interface EvidenceEvent {
  created_at: string;
  created_by?: number | null;
  event_type: string;
  id: number;
  payload_json?: Record<string, unknown>;
}

export interface EvidenceEventList {
  count: number;
  page: number;
  page_size: number;
  results: EvidenceEvent[];
}

export interface EvidenceItem {
  content_type?: string;
  created_at: string;
  episode_id?: number | null;
  file_name: string;
  id: number;
  kind: string;
  patient_id?: number | null;
  retention_class?: string;
  retention_until?: string | null;
  sha256: string;
  size_bytes: number;
  storage_key?: string;
  tags: string[];
  title: string;
}

export interface EvidenceLinkRequest {
  episode_id?: number;
  patient_id?: number;
}

export interface EvidenceLinkResponse {
  episode_id: number | null;
  id: number;
  patient_id: number | null;
}

export interface EvidenceListResponse {
  count: number;
  page: number;
  page_size: number;
  results: EvidenceItem[];
}

export interface EvidenceTagRequest {
  tags: string[];
}

export interface EvidenceTagResponse {
  id: number;
  tags: string[];
}

export interface ExportJob {
  artifact_path?: string;
  created_at: string;
  finished_at?: string | null;
  id: number;
  kind: string;
  params?: Record<string, unknown>;
  status: string;
}

export interface ExportJobList {
  results: ExportJob[];
}

export interface ExportJobRequest {
  kind: string;
  last_days?: number;
}

export interface HealthResponse {
  build_sha: string;
  db_ok: boolean;
  status: string;
  timestamp: string;
  version: string;
}

export interface Integration {
  config?: Record<string, unknown>;
  id: number;
  last_error?: string;
  last_tested_at?: string | null;
  provider: string;
  status: string;
}

export interface IntegrationApiKey {
  created_at: string;
  created_by?: number | null;
  id: number;
  name: string;
  prefix: string;
  revoked_at?: string | null;
}

export interface IntegrationApiKeyCreateRequest {
  name: string;
}

export interface IntegrationApiKeyCreateResponse {
  created_at: string;
  id: number;
  name: string;
  prefix: string;
  revoked_at?: string | null;
  token: string;
}

export interface IntegrationApiKeyList {
  results: IntegrationApiKey[];
}

export interface IntegrationApiKeyRevokeResponse {
  id: number;
  revoked_at: string | null;
}

export interface IntegrationConnectRequest {
  api_key: string;
  sender: string;
}

export interface IntegrationListResponse {
  results: Integration[];
}

export interface IntegrationResponse {
  id: number;
  provider: string;
  status: string;
}

export interface IntegrationTestResponse {
  provider: string;
  status: string;
  tested_at: string;
}

export interface MeResponse {
  email: string | null;
  id: number;
  organization_id: number;
  role: string;
}

export interface Message {
  body: string;
  created_at: string;
  id: number;
  read?: boolean;
  sender_id?: number | null;
}

export interface MessageCreateRequest {
  body: string;
}

export interface MessageReadResponse {
  id: number;
  read_at: string;
}

export interface MetricsResponse {
  last_duration_ms: number;
  total_requests: number;
}

export interface Notification {
  body?: string;
  created_at: string;
  id: number;
  kind?: string;
  read_at?: string | null;
  title: string;
  unread: boolean;
  url?: string;
}

export interface NotificationList {
  count: number;
  page: number;
  page_size: number;
  results: Notification[];
}

export interface NotificationReadResponse {
  id: number;
  read_at?: string | null;
  unread: boolean;
}

export interface OrgInvite {
  created_at: string;
  email: string;
  expires_at: string;
  id: number;
  role: string;
}

export interface OrgInviteList {
  results: OrgInvite[];
}

export interface OrgInviteRequest {
  email: string;
  expires_in_hours?: number;
  role?: string;
}

export interface OrgInviteResponse {
  email: string;
  expires_at: string;
  id: number;
  role: string;
  token: string;
}

export interface OrgMember {
  email: string;
  id: number;
  is_active: boolean;
  role: string;
  user_id: number;
  username?: string;
}

export interface OrgMemberDeactivateResponse {
  id: number;
  is_active: boolean;
}

export interface OrgMemberList {
  results: OrgMember[];
}

export interface OrgMemberRoleRequest {
  role: string;
}

export interface OrgMemberRoleResponse {
  id: number;
  role: string;
}

export interface OrgProfileUpdateRequest {
  name?: string;
}

export interface OrgResponse {
  id: number;
  name: string;
  slug: string;
}

export interface Patient {
  address_line1?: string;
  address_line2?: string;
  city?: string;
  country?: string;
  created_at: string;
  date_of_birth?: string | null;
  email?: string;
  family_name: string;
  given_name: string;
  id: number;
  nhs_number?: string | null;
  phone?: string;
  postal_code?: string;
  region?: string;
  updated_at: string;
}

export interface PatientCreateRequest {
  address_line1?: string;
  address_line2?: string;
  city?: string;
  country?: string;
  date_of_birth?: string;
  email?: string;
  family_name: string;
  given_name: string;
  nhs_number?: string;
  phone?: string;
  postal_code?: string;
  region?: string;
}

export interface PatientList {
  count: number;
  page: number;
  page_size: number;
  results: Patient[];
}

export interface PatientMergeRequest {
  source_id: number;
}

export interface PatientMergeResponse {
  id: number;
  merged_source_id: number;
}

export interface PortalAcceptInviteRequest {
  token: string;
}

export interface PortalAuthResponse {
  expires_at: string;
  organization_id: number;
  patient_id: number;
  role: string;
  token: string;
}

export interface PortalEpisode {
  created_at: string;
  description?: string;
  id: number;
  status: string;
  title: string;
  updated_at: string;
}

export interface PortalEpisodeDetail {
  episode: PortalEpisode;
  timeline: PortalEpisodeEvent[];
}

export interface PortalEpisodeEvent {
  created_at: string;
  event_type: string;
  from_state?: string;
  id: number;
  note?: string;
  to_state?: string;
}

export interface PortalEpisodeList {
  results: PortalEpisode[];
}

export interface PortalLoginRequest {
  email?: string;
  phone?: string;
}

export interface PortalMeResponse {
  email?: string;
  family_name?: string;
  given_name?: string;
  organization_id: number;
  patient_id: number;
  phone?: string;
  role: string;
}

export interface PortalNotification {
  body?: string;
  created_at: string;
  id: number;
  kind?: string;
  read_at?: string | null;
  title: string;
  unread: boolean;
  url?: string;
}

export interface PortalNotificationList {
  count: number;
  page: number;
  page_size: number;
  results: PortalNotification[];
}

export interface PortalNotificationReadResponse {
  id: number;
  read_at?: string | null;
  unread: boolean;
}

export interface ReportJob {
  artifact_path?: string | null;
  id: number;
  interval_days: number;
  last_run_at?: string | null;
  name: string;
  next_run_at?: string | null;
  report_type: string;
  status: string;
}

export interface ReportJobCreateRequest {
  interval_days?: number;
  name: string;
  next_run_at?: string;
  params?: Record<string, unknown>;
  report_type: string;
}

export interface ReportJobList {
  results: ReportJob[];
}

export interface SubmissionRecord {
  due_date: string;
  episode_id?: number | null;
  id: number;
  notes?: string;
  status: string;
  submitted_at?: string | null;
}

export interface SubmissionRecordCreateRequest {
  due_date: string;
  episode_id?: number;
  notes?: string;
  status?: string;
  submitted_at?: string;
}

export interface SubmissionRecordList {
  results: SubmissionRecord[];
}

export interface WorkItem {
  assigned_to?: number | null;
  completed_at?: string | null;
  created_at: string;
  created_by?: number | null;
  due_at?: string | null;
  episode_id?: number | null;
  id: number;
  kind: string;
  sla_breach_at?: string | null;
  sla_breached: boolean;
  status: string;
}

export interface WorkItemAssignRequest {
  assigned_to_id?: number;
}

export interface WorkItemAssignResponse {
  assigned_to: number | null;
  id: number;
  status: string;
}

export interface WorkItemCompleteResponse {
  id: number;
  status: string;
}

export interface WorkItemListResponse {
  count: number;
  page: number;
  page_size: number;
  results: WorkItem[];
}

export interface ApiPaths {
  "/ai-review-items/": {
    GET: AIReviewItemList;
  };
  "/ai/review/": {
    GET: AIReviewListResponse;
  };
  "/ai/review/{review_id}/": {
    GET: AIReviewDetail;
  };
  "/audit-events/": {
    GET: AuditEventList;
  };
  "/billing/plans/": {
    GET: BillingPlanList;
  };
  "/billing/subscription/": {
    GET: BillingSubscription;
  };
  "/compliance/bundles/{bundle_id}/download/": {
    GET: unknown;
  };
  "/compliance/reports/": {
    GET: ReportJobList;
  };
  "/compliance/submissions/": {
    GET: SubmissionRecordList;
  };
  "/conversations/": {
    GET: ConversationListResponse;
  };
  "/conversations/{conversation_id}/": {
    GET: ConversationDetailResponse;
  };
  "/episodes/": {
    GET: EpisodeList;
  };
  "/episodes/{episode_id}/": {
    GET: Episode;
  };
  "/episodes/{episode_id}/compliance/bundles/": {
    GET: EvidenceBundleList;
  };
  "/episodes/{episode_id}/evidence/": {
    GET: EvidenceListResponse;
  };
  "/episodes/{episode_id}/timeline/": {
    GET: EpisodeTimelineResponse;
  };
  "/evidence/": {
    GET: EvidenceListResponse;
  };
  "/evidence/{evidence_id}/": {
    GET: EvidenceItem;
  };
  "/evidence/{evidence_id}/events/": {
    GET: EvidenceEventList;
  };
  "/exports/": {
    GET: ExportJobList;
  };
  "/exports/{export_id}/": {
    GET: ExportJob;
  };
  "/exports/{export_id}/download/": {
    GET: unknown;
  };
  "/health/": {
    GET: HealthResponse;
  };
  "/healthz/": {
    GET: unknown;
  };
  "/integrations/": {
    GET: IntegrationListResponse;
  };
  "/integrations/api-keys/": {
    GET: IntegrationApiKeyList;
  };
  "/me/": {
    GET: MeResponse;
  };
  "/metrics/": {
    GET: MetricsResponse;
  };
  "/notifications/": {
    GET: NotificationList;
  };
  "/orgs/current/": {
    GET: OrgResponse;
  };
  "/orgs/invites/": {
    GET: OrgInviteList;
  };
  "/orgs/members/": {
    GET: OrgMemberList;
  };
  "/patients/": {
    GET: PatientList;
  };
  "/patients/{patient_id}/": {
    GET: Patient;
  };
  "/portal/episodes/": {
    GET: PortalEpisodeList;
  };
  "/portal/episodes/{episode_id}/": {
    GET: PortalEpisodeDetail;
  };
  "/portal/me/": {
    GET: PortalMeResponse;
  };
  "/portal/notifications/": {
    GET: PortalNotificationList;
  };
  "/privacy/consents/": {
    GET: ConsentRecordList;
  };
  "/privacy/dsar/exports/": {
    GET: DsarExportList;
  };
  "/privacy/dsar/exports/{export_id}/download/": {
    GET: unknown;
  };
  "/readyz/": {
    GET: unknown;
  };
  "/work-items/": {
    GET: WorkItemListResponse;
  };
}
